"""Initial revision

Revision ID: 88da0c633dbf
Revises: 9523b4103d49
Create Date: 2025-07-29 23:14:11.097326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88da0c633dbf'
down_revision: Union[str, None] = '9523b4103d49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_username', sa.String(), nullable=False))
    op.add_column('users', sa.Column('given_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('family_name', sa.String(), nullable=False))
    op.drop_column('users', 'job_title')
    op.drop_column('users', 'surname')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), nullable=False))
    op.add_column('users', sa.Column('surname', sa.VARCHAR(), nullable=False))
    op.add_column('users', sa.Column('job_title', sa.VARCHAR(), nullable=False))
    op.drop_column('users', 'family_name')
    op.drop_column('users', 'given_name')
    op.drop_column('users', 'preferred_username')
    # ### end Alembic commands ###
