"""Initial revision

Revision ID: 9523b4103d49
Revises: 5f0fc17aac00
Create Date: 2025-07-29 21:08:41.055844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9523b4103d49'
down_revision: Union[str, None] = '5f0fc17aac00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('job_title', sa.String(), nullable=False))
    op.drop_column('users', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('title', sa.VARCHAR(), nullable=False))
    op.drop_column('users', 'job_title')
    # ### end Alembic commands ###
